/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JTextField;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author emanu
 */
public class frm_murcielago extends javax.swing.JFrame {
    JFileChooser seleccionar= new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    /**
     * Creates new form frm_cadenas
     */
    public frm_murcielago() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.BLACK);
    }

    public String AbrirArchivo(File archivo){
        String documento="";
        try{
            entrada = new FileInputStream(archivo);
            int ascii;
            while ((ascii=entrada.read()) !=-1) {
                char caracter= (char) ascii;
                documento +=caracter;
            }
        }catch (Exception e) {
        }
        return documento;
    }
    
    public String GuardarArchivo(File archivo, String documento) {
        String mensaje = null;
        try{
            salida = new FileOutputStream (archivo) ;
            byte []  bytxt=documento.getBytes();
            salida.write(bytxt);
            mensaje= "Archivo Guardado";
        }catch(Exception e){
            
        }
        return mensaje;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        lbl_mensajeprincipal = new javax.swing.JLabel();
        txt_field = new javax.swing.JScrollPane();
        txt_texto = new javax.swing.JTextField();
        btn_procesar = new javax.swing.JButton();
        lbl_longitud = new javax.swing.JLabel();
        lbl_totalp = new javax.swing.JLabel();
        lbl_primeral = new javax.swing.JLabel();
        lbl_letrac = new javax.swing.JLabel();
        lbl_ultimal = new javax.swing.JLabel();
        lbl_primerap = new javax.swing.JLabel();
        lbl_palabrac = new javax.swing.JLabel();
        lbl_ultimap = new javax.swing.JLabel();
        lbl_repeticionesa = new javax.swing.JLabel();
        lbl_repeticionese = new javax.swing.JLabel();
        lbl_repeticionesi = new javax.swing.JLabel();
        lbl_repeticioneso = new javax.swing.JLabel();
        lbl_repeticionesu = new javax.swing.JLabel();
        lbl_palabraspar = new javax.swing.JLabel();
        lbl_palabrasimpar = new javax.swing.JLabel();
        lbl_clavemurcielago = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_murcielago = new javax.swing.JTextField();
        txt_longitud = new javax.swing.JLabel();
        txt_totalp = new javax.swing.JLabel();
        txt_primeral = new javax.swing.JLabel();
        txt_ultimal = new javax.swing.JLabel();
        txt_letrac = new javax.swing.JLabel();
        txt_primerap = new javax.swing.JLabel();
        txt_palabrac = new javax.swing.JLabel();
        txt_ultimap = new javax.swing.JLabel();
        txt_letraa = new javax.swing.JLabel();
        txt_letrae = new javax.swing.JLabel();
        txt_letrai = new javax.swing.JLabel();
        txt_letrao = new javax.swing.JLabel();
        txt_letrau = new javax.swing.JLabel();
        txt_palabrasp = new javax.swing.JLabel();
        txt_palabrasi = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jm_abrir = new javax.swing.JMenuItem();
        jm_guardar = new javax.swing.JMenuItem();
        jm_guardarComo = new javax.swing.JMenuItem();
        jm_editar = new javax.swing.JMenu();
        jm_copiar = new javax.swing.JMenuItem();
        jm_cortar = new javax.swing.JMenuItem();
        jm_pegar = new javax.swing.JMenuItem();
        jm_buscar = new javax.swing.JMenuItem();
        jm_reemplazar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));

        jInternalFrame1.setBackground(new java.awt.Color(0, 0, 0));
        jInternalFrame1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setVisible(true);

        lbl_mensajeprincipal.setBackground(new java.awt.Color(0, 0, 0));
        lbl_mensajeprincipal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mensajeprincipal.setText("Ingrese un texto o abra un archivo");

        txt_texto.setBackground(new java.awt.Color(102, 102, 102));
        txt_texto.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_field.setViewportView(txt_texto);

        btn_procesar.setText("Procesar");
        btn_procesar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });

        lbl_longitud.setForeground(new java.awt.Color(255, 255, 255));
        lbl_longitud.setText("Longitud del texto");

        lbl_totalp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalp.setText("Total de palabras");

        lbl_primeral.setForeground(new java.awt.Color(255, 255, 255));
        lbl_primeral.setText("Primera letra del texto");

        lbl_letrac.setForeground(new java.awt.Color(255, 255, 255));
        lbl_letrac.setText("Letra central del texto");

        lbl_ultimal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ultimal.setText("Ultima letra del texto");

        lbl_primerap.setForeground(new java.awt.Color(255, 255, 255));
        lbl_primerap.setText("Primera palabra");

        lbl_palabrac.setForeground(new java.awt.Color(255, 255, 255));
        lbl_palabrac.setText("Palabra central");

        lbl_ultimap.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ultimap.setText("Ultima palabra");

        lbl_repeticionesa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_repeticionesa.setText("Repeticiones de \"A\", \"a\",  \"á\"");

        lbl_repeticionese.setForeground(new java.awt.Color(255, 255, 255));
        lbl_repeticionese.setText("Repeticiones de \"E\", \"e\",  \"é\"");

        lbl_repeticionesi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_repeticionesi.setText("Repeticiones de \"I\", \"i\",  \"í\"");

        lbl_repeticioneso.setForeground(new java.awt.Color(255, 255, 255));
        lbl_repeticioneso.setText("Repeticiones de \"O\", \"o\",  \"ó\"");

        lbl_repeticionesu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_repeticionesu.setText("Repeticiones de \"U\", \"u\",  \"ú\"");

        lbl_palabraspar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_palabraspar.setText("Palabras con cantidad de caracteres par");

        lbl_palabrasimpar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_palabrasimpar.setText("Palabras con cantidad de caracteres impar");

        lbl_clavemurcielago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_clavemurcielago.setForeground(new java.awt.Color(255, 255, 255));
        lbl_clavemurcielago.setText("TRADUCCIÓN A CLAVE MURCIELAGO");

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        txt_murcielago.setEditable(false);
        txt_murcielago.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(txt_murcielago);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jm_archivo.setText("Archivo");

        jm_abrir.setText("Abrir");
        jm_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_abrirActionPerformed(evt);
            }
        });
        jm_archivo.add(jm_abrir);

        jm_guardar.setText("Guardar");
        jm_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_guardarActionPerformed(evt);
            }
        });
        jm_archivo.add(jm_guardar);

        jm_guardarComo.setText("Guardar Como");
        jm_guardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_guardarComoActionPerformed(evt);
            }
        });
        jm_archivo.add(jm_guardarComo);

        jMenuBar1.add(jm_archivo);

        jm_editar.setText("Editar");

        jm_copiar.setText("Copiar");
        jm_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_copiarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_copiar);

        jm_cortar.setText("Cortar");
        jm_cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_cortarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_cortar);

        jm_pegar.setText("Pegar");
        jm_pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_pegarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_pegar);

        jm_buscar.setText("Buscar");
        jm_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_buscarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_buscar);

        jm_reemplazar.setText("Reemplazar");
        jm_reemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_reemplazarActionPerformed(evt);
            }
        });
        jm_editar.add(jm_reemplazar);

        jMenuBar1.add(jm_editar);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_mensajeprincipal)
                .addGap(314, 314, 314))
            .addComponent(txt_field, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lbl_clavemurcielago))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(lbl_primerap)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_primerap, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(95, 95, 95))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(lbl_ultimap)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ultimap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(93, 93, 93)))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(lbl_ultimal)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ultimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(lbl_primeral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_primeral, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(lbl_totalp)
                                .addGap(18, 18, 18)
                                .addComponent(txt_totalp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(lbl_longitud)
                                .addGap(23, 23, 23)
                                .addComponent(txt_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(lbl_letrac)
                                .addGap(18, 18, 18)
                                .addComponent(txt_letrac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(lbl_palabrac)
                        .addGap(18, 18, 18)
                        .addComponent(txt_palabrac, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(lbl_repeticionesa)
                        .addGap(35, 35, 35)
                        .addComponent(txt_letraa))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_palabraspar)
                            .addComponent(lbl_repeticionesu)
                            .addComponent(lbl_repeticioneso)
                            .addComponent(lbl_repeticionesi)
                            .addComponent(lbl_repeticionese)
                            .addComponent(lbl_palabrasimpar))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_letrae)
                                    .addComponent(txt_letrai)
                                    .addComponent(txt_letrao)
                                    .addComponent(txt_palabrasi)
                                    .addComponent(txt_letrau)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_palabrasp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_mensajeprincipal)
                .addGap(8, 8, 8)
                .addComponent(txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(txt_letraa)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(btn_procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_primerap, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_primerap, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_palabrac)
                                            .addComponent(txt_palabrac, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_longitud, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_totalp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ultimal)
                                    .addComponent(txt_ultimal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ultimap)
                                    .addComponent(txt_ultimap, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(txt_letrae)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_letrai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_letrao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_letrau)
                                .addGap(28, 28, 28)
                                .addComponent(txt_palabrasi))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(lbl_repeticionesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(lbl_repeticionese)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_repeticionesi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(txt_totalp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(lbl_repeticioneso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_repeticionesu))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_primeral, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_primeral, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)))
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_palabraspar)
                                    .addComponent(txt_palabrasp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_letrac, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_palabrasimpar)
                                        .addComponent(lbl_letrac)))))
                        .addGap(1, 1, 1)))
                .addComponent(lbl_clavemurcielago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
        // TODO add your handling code here:
        // Obtener el texto de entrada
    String cadena = this.txt_texto.getText();

    // Calcular y mostrar la longitud de la cadena
    int longitudCadena = cadena.length();
    txt_longitud.setText(String.valueOf(longitudCadena));

    // Dividir la cadena en palabras y contar
    String[] palabras = cadena.split("\\s+");
    int cantidadPalabras = palabras.length;
    txt_totalp.setText(String.valueOf(cantidadPalabras));

    // Obtener la primera, última y letra central de la cadena
    char primeraLetra = cadena.charAt(0);
    char ultimaLetra = cadena.charAt(longitudCadena - 1);
    char letraCentral;
    int indiceCentralL = longitudCadena / 2;

    if (longitudCadena % 2 == 0) {
    letraCentral = cadena.charAt(indiceCentralL - 1);
    } else {
    letraCentral = cadena.charAt(indiceCentralL);
}

    txt_primeral.setText(String.valueOf(primeraLetra));
    txt_letrac.setText(String.valueOf(ultimaLetra));
    txt_ultimal.setText(String.valueOf(letraCentral));

    // Obtener la primera, última y palabra central
    String primeraPalabra = palabras[0];
    String ultimaPalabra = palabras[cantidadPalabras - 1];
    String palabraCentral;
    int indiceCentralP = cantidadPalabras / 2;

    if (cantidadPalabras % 2 == 0) {
        palabraCentral = palabras[indiceCentralP - 1];
    } else {
        palabraCentral = palabras[indiceCentralP];
    }

    txt_primerap.setText(primeraPalabra);
    txt_palabrac.setText(palabraCentral);
    txt_ultimap.setText(ultimaPalabra);

    // Contar vocales
    int contadorA = 0, contadorE = 0, contadorI = 0, contadorO = 0, contadorU = 0;

    for (char c : cadena.toCharArray()) {
        switch (Character.toLowerCase(c)) {
            case 'a': case 'á': contadorA++; break;
            case 'e': case 'é': contadorE++; break;
            case 'i': case 'í': contadorI++; break;
            case 'o': case 'ó': contadorO++; break;
            case 'u': case 'ú': contadorU++; break;
            }
        }

        txt_letraa.setText(String.valueOf(contadorA));
        txt_letrae.setText(String.valueOf(contadorE));
        txt_letrai.setText(String.valueOf(contadorI));
        txt_letrao.setText(String.valueOf(contadorO));
        txt_letrau.setText(String.valueOf(contadorU));

        // Contar palabras pares e impares
        int contadorPalabrasPar = 0;
        int contadorPalabrasImpar = 0;

    for (String palabra : palabras) {
        if (palabra.length() % 2 == 0) {
            contadorPalabrasPar++;
    } else {
        contadorPalabrasImpar++;
        }
    }

    this.txt_palabrasp.setText(String.valueOf(contadorPalabrasPar));
    this.txt_palabrasi.setText(String.valueOf(contadorPalabrasImpar));

    // Convertir texto a "murciélago"
    Map<Character, String> claveMurcielago = new HashMap<>();
        claveMurcielago.put('a', "7");
        claveMurcielago.put('b', "b");
        claveMurcielago.put('c', "3");
        claveMurcielago.put('d', "d");
        claveMurcielago.put('e', "5");
        claveMurcielago.put('f', "f");
        claveMurcielago.put('g', "8");
        claveMurcielago.put('h', "h");
        claveMurcielago.put('i', "4");
        claveMurcielago.put('j', "j");
        claveMurcielago.put('k', "k");
        claveMurcielago.put('l', "6");
        claveMurcielago.put('m', "0");
        claveMurcielago.put('n', "n");
        claveMurcielago.put('o', "9");
        claveMurcielago.put('p', "p");
        claveMurcielago.put('q', "q");
        claveMurcielago.put('r', "2");
        claveMurcielago.put('s', "s");
        claveMurcielago.put('t', "1");
        claveMurcielago.put('u', "3");
        claveMurcielago.put('v', "v");
        claveMurcielago.put('w', "w");
        claveMurcielago.put('x', "x");
        claveMurcielago.put('y', "y");
        claveMurcielago.put('z', "z");

// Convertir la cadena a murciélago
StringBuilder resultado = new StringBuilder();
for (char c : cadena.toCharArray()) {
    char letra = Character.toLowerCase(c);
    if (c == ' ') {
        resultado.append(" ");
    } else {
        resultado.append(claveMurcielago.getOrDefault(letra, String.valueOf(c)));
    }
}

this.txt_murcielago.setText(resultado.toString());
        //System.out.println(resultado.toString());
    }//GEN-LAST:event_btn_procesarActionPerformed

    private void jm_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_abrirActionPerformed
        // TODO add your handling code here:
        if (seleccionar.showDialog(null, "abrir")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if (archivo.canRead()){
                if (archivo.getName().endsWith("txt")) {
                    String documento=AbrirArchivo(archivo);
                    this.txt_texto.setText(documento);
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo no Compatible");
                }
            }
        }
    }//GEN-LAST:event_jm_abrirActionPerformed

    private void jm_pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_pegarActionPerformed
        // TODO add your handling code here:
        txt_texto.paste();
    }//GEN-LAST:event_jm_pegarActionPerformed

    private void jm_reemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_reemplazarActionPerformed
        // TODO add your handling code here:
        String buscar = JOptionPane.showInputDialog("Buscar:");
String reemplazar = JOptionPane.showInputDialog("Reemplazar con:");

// Obtener el texto actual del JTextField
String texto = txt_texto.getText();

// Verificar que las entradas no sean nulas
if (buscar != null && reemplazar != null) {
    // Reemplazar todas las ocurrencias de la palabra buscada por la nueva palabra
    String nuevoTexto = texto.replaceAll(buscar, reemplazar);
    
    // Actualizar el JTextField con el nuevo texto
    txt_texto.setText(nuevoTexto); 
        }
    }//GEN-LAST:event_jm_reemplazarActionPerformed

    private void jm_guardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_guardarComoActionPerformed
            if (seleccionar.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
                archivo=seleccionar.getSelectedFile();
                if (archivo.getName().endsWith("txt")) {
                    String Documento=this.txt_texto.getText();
                    String mensaje= GuardarArchivo(archivo, Documento);
                    if (mensaje!=null) {
                        JOptionPane.showMessageDialog(null, mensaje);
                    }else{
                        JOptionPane.showMessageDialog(null, "Archivo Compatible");
                    }    
                }
            }
    }//GEN-LAST:event_jm_guardarComoActionPerformed

    private void jm_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_copiarActionPerformed
        // TODO add your handling code here:
        txt_texto.copy(); 
    }//GEN-LAST:event_jm_copiarActionPerformed

    private void jm_cortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_cortarActionPerformed
        // TODO add your handling code here:
        txt_texto.paste();
    }//GEN-LAST:event_jm_cortarActionPerformed

    private void jm_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_buscarActionPerformed
        // TODO add your handling code here:
        String buscar = JOptionPane.showInputDialog("Buscar:");

// Obtener el texto actual del JTextField
String texto = txt_texto.getText();

// Verificar que la entrada no sea nula y que el texto contenga la palabra buscada
if (buscar != null && texto.contains(buscar)) {
    // Encontrar la posición de la palabra buscada en el texto
    int index = texto.indexOf(buscar);
    
    // Seleccionar la palabra encontrada en el JTextField
    txt_texto.select(index, index + buscar.length());
} else {
    // Mostrar un mensaje de error si el texto no se encuentra
    JOptionPane.showMessageDialog(null, "Texto no encontrado");
        }
    }//GEN-LAST:event_jm_buscarActionPerformed

    private void jm_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_guardarActionPerformed
        // TODO add your handling code here:
        // Verifica si ya se ha seleccionado un archivo
    if (archivo != null) {
    // Obtener el texto del JTextArea
    String documento = this.txt_texto.getText();
    
    // Llamar a la función para guardar el documento en el archivo
    String mensaje = GuardarArchivo(archivo, documento);
    
    // Verificar si se recibió un mensaje de error
    if (mensaje != null) {
        // Mostrar mensaje de error o advertencia
        JOptionPane.showMessageDialog(null, mensaje);
    } else {
        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(null, "Archivo guardado correctamente.");
    }
} else {
    // Mostrar mensaje si no se ha seleccionado un archivo
    JOptionPane.showMessageDialog(null, "Primero debe usar 'Guardar como' para seleccionar un archivo.");
    }
    }//GEN-LAST:event_jm_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_murcielago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_murcielago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_murcielago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_murcielago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_murcielago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_procesar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jm_abrir;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenuItem jm_buscar;
    private javax.swing.JMenuItem jm_copiar;
    private javax.swing.JMenuItem jm_cortar;
    private javax.swing.JMenu jm_editar;
    private javax.swing.JMenuItem jm_guardar;
    private javax.swing.JMenuItem jm_guardarComo;
    private javax.swing.JMenuItem jm_pegar;
    private javax.swing.JMenuItem jm_reemplazar;
    private javax.swing.JLabel lbl_clavemurcielago;
    private javax.swing.JLabel lbl_letrac;
    private javax.swing.JLabel lbl_longitud;
    private javax.swing.JLabel lbl_mensajeprincipal;
    private javax.swing.JLabel lbl_palabrac;
    private javax.swing.JLabel lbl_palabrasimpar;
    private javax.swing.JLabel lbl_palabraspar;
    private javax.swing.JLabel lbl_primeral;
    private javax.swing.JLabel lbl_primerap;
    private javax.swing.JLabel lbl_repeticionesa;
    private javax.swing.JLabel lbl_repeticionese;
    private javax.swing.JLabel lbl_repeticionesi;
    private javax.swing.JLabel lbl_repeticioneso;
    private javax.swing.JLabel lbl_repeticionesu;
    private javax.swing.JLabel lbl_totalp;
    private javax.swing.JLabel lbl_ultimal;
    private javax.swing.JLabel lbl_ultimap;
    private javax.swing.JScrollPane txt_field;
    private javax.swing.JLabel txt_letraa;
    private javax.swing.JLabel txt_letrac;
    private javax.swing.JLabel txt_letrae;
    private javax.swing.JLabel txt_letrai;
    private javax.swing.JLabel txt_letrao;
    private javax.swing.JLabel txt_letrau;
    private javax.swing.JLabel txt_longitud;
    private javax.swing.JTextField txt_murcielago;
    private javax.swing.JLabel txt_palabrac;
    private javax.swing.JLabel txt_palabrasi;
    private javax.swing.JLabel txt_palabrasp;
    private javax.swing.JLabel txt_primeral;
    private javax.swing.JLabel txt_primerap;
    private javax.swing.JTextField txt_texto;
    private javax.swing.JLabel txt_totalp;
    private javax.swing.JLabel txt_ultimal;
    private javax.swing.JLabel txt_ultimap;
    // End of variables declaration//GEN-END:variables
}
